### ISSUE TITLE
Toast goes in infinite loop in second appearance

### ISSUE THREAD

**Issue by Samy-33** [xinkule/light-toast#1] opened 2019-06-24 05:55 UTC
when .loading() is called and after that .fail() or .success() then the loading toast takes a long time to hide.

It happens in the second iteration of loading() then fail() or loading() then success().

**Comment by xinkule** [comment] 2019-06-25 01:49
> when .loading() is called and after that .fail() or .success() then the loading toast takes a long time to hide.
> 
> It happens in the second iteration of loading() then fail() or loading() then success().

Thanks for using light-toast, I know the bug, temporarily you can use setTimeout for about 500ms to execute any function after loading() to solve the issue. 

I will find a better solution this week, and publish the upgrade (a little bit busy recently)

**Comment by Samy-33** [comment] 2019-06-27 12:52
Thanks @xinkule. Can you confirm that this issue is because of `raf`?

**Comment by xinkule** [comment] 2019-06-28 06:47
> Thanks @xinkule. Can you confirm that this issue is because of `raf`?

It's because of the scheduling strategy I use, I use `raf` to change the opacity of the toast. 

The problem is, the first fade in or fade out function might be still executing when the next Toast.xxx function comes, then these two get conflicted. I should find a way to ensure the order.

**Comment by xinkule** [comment] 2019-07-28 14:05
@Samy-33 fixed in 0.1.9

**Closed** 2019-07-28 14:04 UTC

**Comment by Samy-33** [comment] 2019-07-30 07:41
@xinkule, thanks. Will test and let you know.
